service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    SQS_URL: ${cf:product-service-${self:provider.stage}.SQSQueueUrl}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::node-aws-s3"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::node-aws-s3/*"
    - Effect: Allow
      Action: "sqs:*"
      Resource:
        - "${cf:product-service-${self:provider.stage}.SQSQueueArn}"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: import
          cors: true
          request:
            parameters:
              paths:
                name: true
          authorizer:
            name: basicAuthorizer
            type: token
            arn: "${cf:authorization-service-${self:provider.stage}.basicAuthorizerArn}"
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: node-aws-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
